### ISSUE TITLE
Cannot load documents

### ISSUE THREAD

**Issue by rosrosros** [ronnieoverby/RavenDB-Linqpad-Driver#11]
After installing my machine and linqpad i can't seem to load any documents from ravendb (version 960)

![2013-06-07_1310](https://f.cloud.github.com/assets/1798386/623368/f10ffb42-cf62-11e2-9c38-768416a3c7f2.png)

Looking at the Url it seems different than what i would expect.

When I try this Url in my browser I get the expected results

**/Databases/offers/docs?query=**

Thanks for a great project!

**Comment by ronnieoverby** [comment]
Please check to see if the latest release fixes your TypeLoadException. #16 pull request may have taken care of this.

**Comment by simon-k** [comment]
I think the reason that I got this error was because I referenced an outdated dll in my solution. 

After updating to the latest driver (0.7.3690.0) I still got the same problem. When I updated assembly paths to use my new assemblies the problem was solved. 

The new driver solved other problems though.

**Comment by ronnieoverby** [comment]
Cool deal. Thanks for checking.
