### ISSUE TITLE
LinqPad4 & 5 - Invalid Driver File

### ISSUE THREAD

**Issue by dedels** [ronnieoverby/RavenDB-Linqpad-Driver#22]
On the latest Linqpad4 & Linqpad5, I get invalid driver file when I try to add the drivers.  I have the paid version.  Is there any other security things I may be doing wrong?

**Comment by dedels** [comment]
Downloading the lpx directly works!  Sorry!

**Comment by ronnieoverby** [comment]
Can you tell me specifically the versions of LP?

**Comment by dedels** [comment]
v5.22.02
v4.57.02
[image: Inline image 2]

I can get this to work by downloading and loading the LPX manually outside
the 'choose a driver' menu.

**Comment by ronnieoverby** [comment]
This issue should be fixed as soon as Joe updates the driver file link in Linqpad.

The new url is: https://rofiles.blob.core.windows.net/public/RavenLinqpadDriver.lpx

Prior to moving the file to azure, I was hosting it on my companies website. Recently, that site was replaced and that's why the driver is failing to install (basically 404).

**Comment by ronnieoverby** [comment]
Fixed.
